ALTER TRIGGER TR_LENHDAT_INSERT ON DBO.LENHDAT
AFTER INSERT
AS 
BEGIN
	DECLARE @LOAIGD NCHAR(1), @MACP NCHAR(7),@GIA INT
	SELECT @LOAIGD=LOAIGD, @MACP = MACP, @GIA = GIADAT FROM Inserted
	IF @MACP NOT IN (SELECT MACP FROM dbo.BANGGIA)
	BEGIN
	    INSERT dbo.BANGGIA (MACP) VALUES (@MACP)
	END
	
	IF @LOAIGD = 'M'
	BEGIN
		DECLARE @G_M_1 INT, @KL_M_1 INT, @G_M_2 INT, @KL_M_2 INT, @G_M_3 INT, @KL_M_3 INT
		EXEC TOP_M @MACP, 1, @G_M_1 OUTPUT, @KL_M_1 OUTPUT
		EXEC TOP_M @MACP, 2, @G_M_2 OUTPUT, @KL_M_2 OUTPUT
		EXEC TOP_M @MACP, 3, @G_M_3 OUTPUT, @KL_M_3 OUTPUT
		UPDATE dbo.BANGGIA SET GIA_M_MOT = @G_M_1, GIA_M_HAI = @G_M_2, GIA_M_BA = @G_M_3, KL_M_MOT = @KL_M_1, KL_M_HAI = @KL_M_2, KL_M_BA = @KL_M_3
		WHERE MACP = @MACP
	END
	ELSE IF @LOAIGD = 'B'
	BEGIN
		DECLARE @G_B_1 INT, @KL_B_1 INT, @G_B_2 INT, @KL_B_2 INT, @G_B_3 INT, @KL_B_3 INT
		EXEC TOP_B @MACP, 1, @G_B_1 OUTPUT, @KL_B_1 OUTPUT
		EXEC TOP_B @MACP, 2, @G_B_2 OUTPUT, @KL_B_2 OUTPUT
		EXEC TOP_B @MACP, 3, @G_B_3 OUTPUT, @KL_B_3 OUTPUT
		UPDATE dbo.BANGGIA SET GIA_B_MOT = @G_B_1, GIA_B_HAI = @G_B_2, GIA_B_BA = @G_B_3, KL_B_MOT = @KL_B_1, KL_B_HAI = @KL_B_2, KL_B_BA = @KL_B_3
		WHERE MACP = @MACP
	END
	ELSE
	BEGIN
		RAISERROR (N'NHẬP KHÔNG HỢP LỆ',16,10) WITH NOWAIT
		ROLLBACK TRANSACTION
	END
END
GO

ALTER TRIGGER TR_LENHDAT_DELETE ON dbo.LENHDAT
AFTER DELETE
AS
BEGIN
	DECLARE @LOAIGD NCHAR(1), @MACP NCHAR(7)
	SELECT @LOAIGD=LOAIGD, @MACP = MACP FROM Deleted
	IF @MACP NOT IN (SELECT MACP FROM dbo.LENHDAT)
		DELETE FROM dbo.BANGGIA WHERE MACP = @MACP
	IF @LOAIGD = 'M'
	BEGIN
		DECLARE @G_M_1 INT, @KL_M_1 INT, @G_M_2 INT, @KL_M_2 INT, @G_M_3 INT, @KL_M_3 INT
		EXEC TOP_M @MACP, 1, @G_M_1 OUTPUT, @KL_M_1 OUTPUT
		EXEC TOP_M @MACP, 2, @G_M_2 OUTPUT, @KL_M_2 OUTPUT
		EXEC TOP_M @MACP, 3, @G_M_3 OUTPUT, @KL_M_3 OUTPUT
		UPDATE dbo.BANGGIA SET GIA_M_MOT = @G_M_1, GIA_M_HAI = @G_M_2, GIA_M_BA = @G_M_3, KL_M_MOT = @KL_M_1, KL_M_HAI = @KL_M_2, KL_M_BA = @KL_M_3
		WHERE MACP = @MACP
	END
	IF @LOAIGD = 'M'
	BEGIN
		DECLARE @G_B_1 INT, @KL_B_1 INT, @G_B_2 INT, @KL_B_2 INT, @G_B_3 INT, @KL_B_3 INT
		EXEC TOP_B @MACP, 1, @G_B_1 OUTPUT, @KL_B_1 OUTPUT
		EXEC TOP_B @MACP, 2, @G_B_2 OUTPUT, @KL_B_2 OUTPUT
		EXEC TOP_B @MACP, 3, @G_B_3 OUTPUT, @KL_B_3 OUTPUT
		UPDATE dbo.BANGGIA SET GIA_B_MOT = @G_B_1, GIA_B_HAI = @G_B_2, GIA_B_BA = @G_B_3, KL_B_MOT = @KL_B_1, KL_B_HAI = @KL_B_2, KL_B_BA = @KL_B_3
		WHERE MACP = @MACP
	END
END
GO

INSERT dbo.LENHDAT
(
    MACP,
    NGAYDAT,
    LOAIGD,
    LOAILENH,
    SOLUONG,
    GIADAT,
    TRANGTHAILENH
)
VALUES
(   N'BID',       -- MACP - nchar(7)
    GETDATE(), -- NGAYDAT - datetime
    N'M',       -- LOAIGD - nchar(1)
    N'LO',       -- LOAILENH - nchar(10)
    1000,         -- SOLUONG - int
    9000,       -- GIADAT - float
    N''        -- TRANGTHAILENH - nvarchar(30)
    )
GO

CREATE TRIGGER TR_LENHKHOP_INSERT ON dbo.LENHKHOP
AFTER INSERT
AS
BEGIN
    DECLARE @IDLENHDAT INT, @KL INT, @GIA INT, @MACP NCHAR(7), @TONG_KL INT
	SELECT @IDLENHDAT = Inserted.IDLENHDAT, @KL = Inserted.SOLUONGKHOP, @GIA = Inserted.GIAKHOP  FROM Inserted
	EXEC THONGTIN_ID @IDLENHDAT, @TONG_KL OUTPUT, @MACP OUTPUT
	UPDATE dbo.BANGGIA SET GIA_KHOP_MOI = @GIA, KL_KHOP_MOI = @KL, TONG_KL_KHOP = @TONG_KL WHERE MACP = @MACP
END
GO

SELECT MACP, SUM(SOLUONGKHOP)  FROM dbo.LENHDAT, dbo.LENHKHOP 
WHERE ID = 51 AND ID = IDLENHDAT
GROUP BY MACP

ALTER PROC THONGTIN_ID
@ID INT, @TONG_KL INT OUTPUT, @MACP NCHAR(7) OUTPUT
AS
BEGIN
    SELECT @MACP = MACP, @TONG_KL = SUM(SOLUONGKHOP) FROM dbo.LENHDAT, dbo.LENHKHOP
	WHERE ID = @ID AND ID = IDLENHDAT
	GROUP BY MACP
END


INSERT dbo.LENHKHOP
(
    NGAYKHOP,
    SOLUONGKHOP,
    GIAKHOP,
    IDLENHDAT
)
VALUES
(   GETDATE(), -- NGAYKHOP - datetime
    1000,         -- SOLUONGKHOP - int
    10000,       -- GIAKHOP - float
    50          -- IDLENHDAT - int
    )

DELETE FROM dbo.LENHDAT
DELETE FROM dbo.LENHKHOP
DELETE FROM dbo.BANGGIA

INSERT dbo.LENHDAT
(
    MACP,
    NGAYDAT,
    LOAIGD,
    LOAILENH,
    SOLUONG,
    GIADAT,
    TRANGTHAILENH
)
VALUES
(   N'ACB',       -- MACP - nchar(7)
    GETDATE(), -- NGAYDAT - datetime
    N'M',       -- LOAIGD - nchar(1)
    N'LO',       -- LOAILENH - nchar(10)
    15,         -- SOLUONG - int
    7,       -- GIADAT - float
    N'CHỜ KHỚP'        -- TRANGTHAILENH - nvarchar(30)
    )
INSERT dbo.LENHDAT
(
    MACP,
    NGAYDAT,
    LOAIGD,
    LOAILENH,
    SOLUONG,
    GIADAT,
    TRANGTHAILENH
)
VALUES
(   N'ACB',       -- MACP - nchar(7)
    GETDATE(), -- NGAYDAT - datetime
    N'B',       -- LOAIGD - nchar(1)
    N'LO',       -- LOAILENH - nchar(10)
    15,         -- SOLUONG - int
    7,       -- GIADAT - float
    N''        -- TRANGTHAILENH - nvarchar(30)
    )

INSERT dbo.LENHKHOP
(
    NGAYKHOP,
    SOLUONGKHOP,
    GIAKHOP,
    IDLENHDAT
)
VALUES
(   GETDATE(), -- NGAYKHOP - datetime
    30,         -- SOLUONGKHOP - int
    6,       -- GIAKHOP - float
    59          -- IDLENHDAT - int
    )