INSERT dbo.LENHDAT(MACP,NGAYDAT,LOAIGD,LOAILENH,SOLUONG,GIADAT,TRANGTHAILENH) VALUES(N'BID',GETDATE(),N'M',
N'LO',10, 10,N'Chưa Khớp')

INSERT dbo.LENHDAT(MACP,NGAYDAT,LOAIGD,LOAILENH,SOLUONG,GIADAT,TRANGTHAILENH) VALUES(N'ACB',GETDATE(),N'M',
N'LO',12, 15,N'Chưa Khớp')

INSERT dbo.LENHDAT(MACP,NGAYDAT,LOAIGD,LOAILENH,SOLUONG,GIADAT,TRANGTHAILENH) VALUES(N'ACB',GETDATE(),N'M',
N'LO',10, 17,N'Chưa Khớp')

INSERT dbo.LENHDAT(MACP,NGAYDAT,LOAIGD,LOAILENH,SOLUONG,GIADAT,TRANGTHAILENH) VALUES(N'ACB',GETDATE(),N'M',
N'LO',10, 20,N'Chưa Khớp')

INSERT dbo.LENHDAT(MACP,NGAYDAT,LOAIGD,LOAILENH,SOLUONG,GIADAT,TRANGTHAILENH) VALUES(N'ACB',GETDATE(),N'B',
N'LO',12, 27,N'Chưa Khớp')

INSERT dbo.LENHDAT(MACP,NGAYDAT,LOAIGD,LOAILENH,SOLUONG,GIADAT,TRANGTHAILENH) VALUES(N'ACB',GETDATE(),N'B',
N'LO',10, 31,N'Chưa Khớp')

INSERT dbo.LENHDAT(MACP,NGAYDAT,LOAIGD,LOAILENH,SOLUONG,GIADAT,TRANGTHAILENH) VALUES(N'ACB',GETDATE(),N'B',
N'LO',10, 36,N'Chưa Khớp')

INSERT dbo.LENHKHOP(NGAYKHOP,SOLUONGKHOP,GIAKHOP,IDLENHDAT) VALUES (GETDATE(), 10, 36, 1089)

INSERT dbo.LENHKHOP(NGAYKHOP,SOLUONGKHOP,GIAKHOP,IDLENHDAT) VALUES (GETDATE(), 10, 36, 1084)